"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";
import { format } from "date-fns";
import { Printer, Filter } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { formatINR } from "@/lib/utils";

export interface DayEntry {
  date: string;
  type: "Purchase" | "Sale" | "Payment" | "Receipt" | "Expense";
  particulars: string;
  ref: string | null;
  amount: number;
}

const TONE: Record<DayEntry["type"], "default" | "secondary" | "destructive" | "success" | "outline"> = {
  Purchase: "secondary",
  Sale: "outline",
  Payment: "destructive",
  Receipt: "success",
  Expense: "destructive",
};

export function DayBookView({
  companyName,
  from,
  to,
  entries,
}: {
  companyName: string;
  from: string;
  to: string;
  entries: DayEntry[];
}) {
  const router = useRouter();
  const params = useSearchParams();
  const [f, setF] = useState(from);
  const [t, setT] = useState(to);

  function apply() {
    const p = new URLSearchParams(params.toString());
    p.set("from", f);
    p.set("to", t);
    router.push(`/daybook?${p.toString()}`);
  }

  // group by date
  const byDate = new Map<string, DayEntry[]>();
  for (const e of entries) {
    const arr = byDate.get(e.date) ?? [];
    arr.push(e);
    byDate.set(e.date, arr);
  }
  const dates = Array.from(byDate.keys()).sort();

  return (
    <div className="space-y-6">
      <div className="no-print flex flex-wrap items-end gap-3">
        <div className="space-y-1.5">
          <Label htmlFor="from">From</Label>
          <Input id="from" type="date" value={f} onChange={(e) => setF(e.target.value)} />
        </div>
        <div className="space-y-1.5">
          <Label htmlFor="to">To</Label>
          <Input id="to" type="date" value={t} onChange={(e) => setT(e.target.value)} />
        </div>
        <Button variant="outline" onClick={apply}>
          <Filter className="h-4 w-4" />
          Apply
        </Button>
        <Button onClick={() => window.print()}>
          <Printer className="h-4 w-4" />
          Download PDF
        </Button>
      </div>

      <div className="print-area space-y-6">
        <div className="border-b pb-3">
          <h1 className="text-xl font-bold">{companyName}</h1>
          <p className="text-sm text-muted-foreground">
            Day Book · {format(new Date(from), "dd MMM yyyy")} –{" "}
            {format(new Date(to), "dd MMM yyyy")}
          </p>
        </div>

        {dates.length === 0 ? (
          <p className="text-sm text-muted-foreground">
            No transactions in this period.
          </p>
        ) : (
          dates.map((d) => (
            <section key={d} className="space-y-1">
              <h2 className="text-sm font-semibold">
                {format(new Date(d), "EEEE, dd MMM yyyy")}
              </h2>
              <table className="w-full border-collapse text-sm">
                <tbody>
                  {byDate.get(d)!.map((e, i) => (
                    <tr key={i} className="border-b">
                      <td className="p-2 w-24">
                        <Badge variant={TONE[e.type]}>{e.type}</Badge>
                      </td>
                      <td className="p-2">{e.particulars}</td>
                      <td className="p-2 text-muted-foreground">{e.ref ?? ""}</td>
                      <td className="p-2 text-right font-medium">
                        {formatINR(e.amount)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </section>
          ))
        )}

        <p className="pt-4 text-xs text-muted-foreground">
          Generated by BOS on {format(new Date(), "dd MMM yyyy, HH:mm")}
        </p>
      </div>
    </div>
  );
}
