"use client";

import { format } from "date-fns";
import { Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatINR } from "@/lib/utils";

export interface LedgerRow {
  entry_date: string;
  narration: string | null;
  entry_type: string; // debit | credit
  amount: number;
  reference_number: string | null;
}

export function StatementView({
  companyName,
  partyName,
  rows,
}: {
  companyName: string;
  partyName: string;
  rows: LedgerRow[];
}) {
  // Running balance: credit increases payable (we owe), debit reduces it.
  let running = 0;
  const withBalance = rows.map((r) => {
    running += (r.entry_type === "credit" ? 1 : -1) * Number(r.amount);
    return { ...r, balance: running };
  });

  const owe = running; // positive => we owe the party
  const balanceLabel =
    owe > 0
      ? `Payable (we owe): ${formatINR(owe)}`
      : owe < 0
        ? `Receivable (they owe): ${formatINR(-owe)}`
        : "Settled: ₹0";

  return (
    <div className="space-y-4">
      <div className="no-print flex justify-end">
        <Button onClick={() => window.print()}>
          <Printer className="h-4 w-4" />
          Download PDF
        </Button>
      </div>

      <div className="print-area space-y-4">
        <div className="border-b pb-3">
          <h1 className="text-xl font-bold">{companyName}</h1>
          <p className="text-sm text-muted-foreground">
            Statement of Account — {partyName}
          </p>
          <p className="text-sm font-semibold">{balanceLabel}</p>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr className="border-b text-left">
                <th className="p-2">Date</th>
                <th className="p-2">Particulars</th>
                <th className="p-2">Ref</th>
                <th className="p-2 text-right">Debit</th>
                <th className="p-2 text-right">Credit</th>
                <th className="p-2 text-right">Balance</th>
              </tr>
            </thead>
            <tbody>
              {withBalance.length === 0 ? (
                <tr>
                  <td colSpan={6} className="p-4 text-center text-muted-foreground">
                    No ledger entries yet for this party.
                  </td>
                </tr>
              ) : (
                withBalance.map((r, i) => (
                  <tr key={i} className="border-b">
                    <td className="p-2">
                      {format(new Date(r.entry_date), "dd-MM-yy")}
                    </td>
                    <td className="p-2">{r.narration ?? "—"}</td>
                    <td className="p-2">{r.reference_number ?? "—"}</td>
                    <td className="p-2 text-right">
                      {r.entry_type === "debit" ? formatINR(r.amount) : "—"}
                    </td>
                    <td className="p-2 text-right">
                      {r.entry_type === "credit" ? formatINR(r.amount) : "—"}
                    </td>
                    <td className="p-2 text-right font-medium">
                      {formatINR(Math.abs(r.balance))}{" "}
                      <span className="text-xs text-muted-foreground">
                        {r.balance >= 0 ? "Cr" : "Dr"}
                      </span>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        <p className="pt-2 text-xs text-muted-foreground">
          Generated by BOS on {format(new Date(), "dd MMM yyyy, HH:mm")}
        </p>
      </div>
    </div>
  );
}
