-- ============================================================
-- 0004 — PURCHASES & SALES
-- ============================================================

create table if not exists public.purchase_entries (
  id                uuid primary key default gen_random_uuid(),
  company_id        uuid references public.companies(id) on delete cascade,
  entry_number      text not null,
  entry_date        date not null,
  supplier_id       uuid references public.parties(id),
  vehicle_id        uuid references public.vehicles(id),
  weighment_slip_id uuid references public.weighment_slips(id),
  product_id        uuid references public.products(id),
  quantity_kg       numeric(15,3),
  bags_count        integer,
  rate_per_kg       numeric(10,4),
  rate_per_bag      numeric(10,2),
  subtotal          numeric(15,2),
  freight           numeric(15,2) default 0,
  loading_charges   numeric(15,2) default 0,
  other_charges     numeric(15,2) default 0,
  discount_amount   numeric(15,2) default 0,
  taxable_amount    numeric(15,2),
  cgst_rate         numeric(5,2) default 0,
  cgst_amount       numeric(15,2) default 0,
  sgst_rate         numeric(5,2) default 0,
  sgst_amount       numeric(15,2) default 0,
  igst_rate         numeric(5,2) default 0,
  igst_amount       numeric(15,2) default 0,
  total_amount      numeric(15,2) not null,
  advance_paid      numeric(15,2) default 0,
  balance_due       numeric(15,2),
  payment_status    text default 'pending',  -- pending | partial | paid
  due_date          date,
  notes             text,
  custom_fields     jsonb default '{}'::jsonb,
  is_cancelled      boolean default false,
  cancelled_reason  text,
  created_by        uuid references auth.users(id),
  created_at        timestamptz default now(),
  updated_at        timestamptz default now(),
  unique(company_id, entry_number)
);

create table if not exists public.purchase_attachments (
  id              uuid primary key default gen_random_uuid(),
  purchase_id     uuid references public.purchase_entries(id) on delete cascade,
  document_id     uuid,
  attachment_type text,
  created_at      timestamptz default now()
);

create table if not exists public.sale_entries (
  id                uuid primary key default gen_random_uuid(),
  company_id        uuid references public.companies(id) on delete cascade,
  entry_number      text not null,
  invoice_number    text,
  entry_date        date not null,
  customer_id       uuid references public.parties(id),
  vehicle_id        uuid references public.vehicles(id),
  weighment_slip_id uuid references public.weighment_slips(id),
  product_id        uuid references public.products(id),
  quantity_kg       numeric(15,3),
  bags_count        integer,
  rate_per_kg       numeric(10,4),
  rate_per_bag      numeric(10,2),
  subtotal          numeric(15,2),
  freight           numeric(15,2) default 0,
  unloading_charges numeric(15,2) default 0,
  other_charges     numeric(15,2) default 0,
  discount_amount   numeric(15,2) default 0,
  taxable_amount    numeric(15,2),
  cgst_rate         numeric(5,2) default 0,
  cgst_amount       numeric(15,2) default 0,
  sgst_rate         numeric(5,2) default 0,
  sgst_amount       numeric(15,2) default 0,
  igst_rate         numeric(5,2) default 0,
  igst_amount       numeric(15,2) default 0,
  total_amount      numeric(15,2) not null,
  advance_received  numeric(15,2) default 0,
  balance_due       numeric(15,2),
  payment_status    text default 'pending',
  due_date          date,
  notes             text,
  custom_fields     jsonb default '{}'::jsonb,
  is_cancelled      boolean default false,
  cancelled_reason  text,
  created_by        uuid references auth.users(id),
  created_at        timestamptz default now(),
  updated_at        timestamptz default now(),
  unique(company_id, entry_number)
);
